### ISSUE TITLE
Coal Generator disappearing after breaking

### ISSUE THREAD

**Issue by TriTank** [TheMCBrothers/Useful-Machinery#6]
When I break any machine its completely disappears and doesn't drop anything almost like I'm in creative. If I put down the compactor it crashes my game.
Here's the crash log:
[23:03:09] [Server thread/ERROR]: Encountered an unexpected exception
java.lang.NoClassDefFoundError: Could not initialize class themcbros.usefulmachinery.machine.CompactorMode
	at themcbros.usefulmachinery.blockentity.CompactorBlockEntity.<init>(CompactorBlockEntity.java:60) ~[usefulmachinery-1.18-1.3.0.jar%23174!:1.3.0]
	at net.minecraft.world.level.block.entity.BlockEntityType.m_155264_(BlockEntityType.java:91) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at themcbros.usefulmachinery.blocks.CompactorBlock.m_142194_(CompactorBlock.java:17) ~[usefulmachinery-1.18-1.3.0.jar%23174!:1.3.0]
	at net.minecraft.world.level.chunk.LevelChunk.m_6978_(LevelChunk.java:251) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.world.level.Level.m_6933_(Level.java:202) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.world.level.Level.m_7731_(Level.java:179) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.world.item.BlockItem.m_7429_(BlockItem.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.world.item.BlockItem.m_40576_(BlockItem.java:66) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.world.item.BlockItem.m_6225_(BlockItem.java:46) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraftforge.common.ForgeHooks.onPlaceItemIntoWorld(ForgeHooks.java:574) ~[forge-1.18.1-39.0.9-universal.jar%23187!:?]
	at net.minecraft.world.item.ItemStack.m_41661_(ItemStack.java:212) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:350) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:975) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:30) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:21) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:765) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:748) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:742) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:728) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:672) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:258) ~[client-1.18.1-20211210.034407-srg.jar%23183!:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]

Here are my mods.
https://ibb.co/wy27qx6
https://ibb.co/xz2nCfw
https://ibb.co/1GY1jQ8

**Comment by TheMCCrazyMan** [comment]
Hey, 
This issue should be solved. If not please write a comment on this ticket ;-)

**Comment by TriTank** [comment]
Is there a way I can use the updated mod and keep my original world?
I'm getting this error now when using the new mod, thanks again for all your work!
`[09:24:53] [Worker-Main-20/ERROR]: Couldn't read tag list minecraft:mineable/pickaxe from minecraft:tags/blocks/mineable/pickaxe.json in data pack compactmachines-4.0.0-beta.3.jar
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.tags.TagLoader.m_144495_(TagLoader.java:56) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.tags.TagLoader.m_144544_(TagLoader.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.tags.TagManager.m_144587_(TagManager.java:74) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:592) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:703) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:908) ~[gson-2.8.8.jar%2325!:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	... 11 more
[09:24:53] [Worker-Main-20/ERROR]: Couldn't read tag list minecraft:needs_iron_tool from minecraft:tags/blocks/needs_iron_tool.json in data pack compactmachines-4.0.0-beta.3.jar
com.google.gson.JsonParseException: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:505) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.GsonHelper.m_13776_(GsonHelper.java:542) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.tags.TagLoader.m_144495_(TagLoader.java:56) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.tags.TagLoader.m_144544_(TagLoader.java:138) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.tags.TagManager.m_144587_(TagManager.java:74) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) [?:?]
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) [?:?]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) [?:?]
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) [?:?]
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) [?:?]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) [?:?]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) [?:?]
Caused by: com.google.gson.stream.MalformedJsonException: Use JsonReader.setLenient(true) to accept malformed JSON at line 1 column 1 path $
	at com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1562) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.stream.JsonReader.checkLenient(JsonReader.java:1403) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:592) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.stream.JsonReader.peek(JsonReader.java:424) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:703) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:701) ~[gson-2.8.8.jar%2325!:?]
	at com.google.gson.internal.bind.TypeAdapters$35$1.read(TypeAdapters.java:908) ~[gson-2.8.8.jar%2325!:?]
	at net.minecraft.util.GsonHelper.m_13780_(GsonHelper.java:503) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	... 11 more
[09:24:55] [Render thread/INFO]: Loaded EnvironmentData recipe with id: cagedmobs:envs/end
[09:24:55] [Render thread/INFO]: Loaded MobData recipe with id: aquaculture:mobs/gar
[09:24:55] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.NoClassDefFoundError: themcbros/usefulfoundation/init/FoundationItems
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2072) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1903) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.Minecraft.m_91200_(Minecraft.java:1872) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101744_(WorldSelectionList.java:436) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101704_(WorldSelectionList.java:342) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_6375_(WorldSelectionList.java:273) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.gui.components.AbstractSelectionList.m_6375_(AbstractSelectionList.java:323) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.MouseHandler.lambda$onPress$0(MouseHandler.java:88) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:527) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:101) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%230!:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%236!:build 10]
	at org.lwjgl.glfw.GLFW.glfwWaitEventsTimeout(GLFW.java:3174) ~[lwjgl-glfw-3.2.2.jar%230!:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69830_(RenderSystem.java:220) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1065) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:660) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:45) ~[fmlloader-1.18.1-39.0.10.jar%2351!:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.0.7.jar%2340!:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90) [bootstraplauncher-0.1.17.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:57) [ForgeWrapper-mmc3.jar:mmc3]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
Caused by: java.lang.NoClassDefFoundError: themcbros/usefulfoundation/init/FoundationItems
	at themcbros.usefulmachinery.machine.CompactorMode.<clinit>(CompactorMode.java:17) ~[usefulmachinery-1.18.1-1.4.0.jar%23196!:1.4.0]
	at themcbros.usefulmachinery.recipes.CompactingRecipe$Serializer.fromJson(CompactingRecipe.java:127) ~[usefulmachinery-1.18.1-1.4.0.jar%23196!:1.4.0]
	at themcbros.usefulmachinery.recipes.CompactingRecipe$Serializer.m_6729_(CompactingRecipe.java:97) ~[usefulmachinery-1.18.1-1.4.0.jar%23196!:1.4.0]
	at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:144) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:60) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:35) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2071) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	... 46 more
Caused by: java.lang.ClassNotFoundException: themcbros.usefulfoundation.init.FoundationItems
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:132) ~[securejarhandler-0.9.54.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at themcbros.usefulmachinery.machine.CompactorMode.<clinit>(CompactorMode.java:17) ~[usefulmachinery-1.18.1-1.4.0.jar%23196!:1.4.0]
	at themcbros.usefulmachinery.recipes.CompactingRecipe$Serializer.fromJson(CompactingRecipe.java:127) ~[usefulmachinery-1.18.1-1.4.0.jar%23196!:1.4.0]
	at themcbros.usefulmachinery.recipes.CompactingRecipe$Serializer.m_6729_(CompactingRecipe.java:97) ~[usefulmachinery-1.18.1-1.4.0.jar%23196!:1.4.0]
	at net.minecraft.world.item.crafting.RecipeManager.m_44045_(RecipeManager.java:144) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:60) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.world.item.crafting.RecipeManager.m_5787_(RecipeManager.java:35) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:71) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:151) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:125) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:134) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	at net.minecraft.client.Minecraft.m_91190_(Minecraft.java:2071) ~[client-1.18.1-20211210.034407-srg.jar%23207!:?]
	... 46 more
`

**Comment by TriTank** [comment]
Nevermind found out it requires Useful Foundation now. Might want to update that on your page :)
